name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get
      run: go get -d -v ./...
      
    - name: Mod
      run: go mod download
      
    - name: Vendor
      run: go mod vendor
      
    - name: Verify
      run: go mod verify
      
    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...
